### ISSUE TITLE
Preserve context

### ISSUE THREAD

**Issue by QuentinRoy** [wuct/raf-throttle#35]
On some instances, one might want to use this to throttle an object's method.
In this case, the fact that `raf-throttle` does not preserve the context it is called with (i.e. `this`) can be an issue.

**Comment by wuct** [comment]
Yes, we should preserve the context.

**Comment by me-andre** [comment]
LOL
Why ever do we need to preserve the context of the 1st call, but not the last?
The context is a kind of a "hidden" argument and what people expect from a throttled or a debounced function is being invoked with the *most recent* arguments it has received.
Moreover, actually this "fix" does not make `raf-throttle` preserve the 1st context, but just the 1st after the last animation frame (a library consumer doesn't want to care about when animation frame happened, right?). Take a look here https://github.com/wuct/raf-throttle/pull/64
I would say this is unpredictable and unreliable behavior.
What "industry standard" libs (e.g. `lodash`) do is making no assumption about context.

**Comment by wuct** [comment]
> this "fix" does not make raf-throttle preserve the 1st context, but just the 1st after the last animation frame 

Actually, the current behavior is expected. I can agree that the commit message and the name of the test should be more clear.

> What "industry standard" libs (e.g. lodash) do is making no assumption about context.

It seems like lodash also keeps the [context](https://github.com/lodash/lodash/blob/master/debounce.js#L189). I am not sure what do you mean by "no assumption". Can you explain more?

**Comment by me-andre** [comment]
Regarding the `lodash`, I made a mistake. It does keep the *last* context.
https://gist.github.com/me-andre/05167d171c7b2c0b2df4779272f87c3d
Keeping the last context is predictable thought. As a developer you always know under which context the function got called the last time.

But keeping the first context after the actual invocation is unreliable. You don't know when the animation frames happen. You just want to throttle a function but inside it you get close-to-random context value. How can that be an expected behavior?

**Comment by wuct** [comment]
Yes, now I can see it is a bug. Thanks for your explanation again :)
